//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolvisSC2Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolvisSC2Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string AllClassesFile {
            get {
                return ResourceManager.GetString("AllClassesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formula has runtime error, =&gt; see StackTrace.txt ähnelt.
        /// </summary>
        internal static string CalculatorProxyRuntimeError {
            get {
                return ResourceManager.GetString("CalculatorProxyRuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new Day ähnelt.
        /// </summary>
        internal static string ChartControlNewDay {
            get {
                return ResourceManager.GetString("ChartControlNewDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compile Error:  ähnelt.
        /// </summary>
        internal static string CodeBuilderCompileError {
            get {
                return ResourceManager.GetString("CodeBuilderCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free formulas ähnelt.
        /// </summary>
        internal static string CodeBuilderFreeFormulas {
            get {
                return ResourceManager.GetString("CodeBuilderFreeFormulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search directory for file zeitplan.txt ähnelt.
        /// </summary>
        internal static string ConfigEditorSearch {
            get {
                return ResourceManager.GetString("ConfigEditorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Burner KW ähnelt.
        /// </summary>
        internal static string ConfigManagerBurnerKW {
            get {
                return ResourceManager.GetString("ConfigManagerBurnerKW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flow HC1 (act. - set) ähnelt.
        /// </summary>
        internal static string ConfigManagerFlowHC1 {
            get {
                return ResourceManager.GetString("ConfigManagerFlowHC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formula ähnelt.
        /// </summary>
        internal static string ConfigManagerFormula {
            get {
                return ResourceManager.GetString("ConfigManagerFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ideal Formula ähnelt.
        /// </summary>
        internal static string ConfigManagerIdealFormula {
            get {
                return ResourceManager.GetString("ConfigManagerIdealFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solar KW ähnelt.
        /// </summary>
        internal static string ConfigManagerSolarKW {
            get {
                return ResourceManager.GetString("ConfigManagerSolarKW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solvis Formula ähnelt.
        /// </summary>
        internal static string ConfigManagerSolvisFormula {
            get {
                return ResourceManager.GetString("ConfigManagerSolvisFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SunPosition ähnelt.
        /// </summary>
        internal static string ConfigManagerSunPosition {
            get {
                return ResourceManager.GetString("ConfigManagerSunPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Countings ähnelt.
        /// </summary>
        internal static string CountingListActionCountings {
            get {
                return ResourceManager.GetString("CountingListActionCountings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solvis file error ähnelt.
        /// </summary>
        internal static string DataManagerSolvisFileError {
            get {
                return ResourceManager.GetString("DataManagerSolvisFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string FileToInt32ListError {
            get {
                return ResourceManager.GetString("FileToInt32ListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outdoor temp. ähnelt.
        /// </summary>
        internal static string HeatCurveAxisXTitle {
            get {
                return ResourceManager.GetString("HeatCurveAxisXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flow temp. ähnelt.
        /// </summary>
        internal static string HeatCurveAxisYTitle {
            get {
                return ResourceManager.GetString("HeatCurveAxisYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run of the curve ähnelt.
        /// </summary>
        internal static string HeatCurveRunCurve {
            get {
                return ResourceManager.GetString("HeatCurveRunCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameters ähnelt.
        /// </summary>
        internal static string ParameterListActionParameters {
            get {
                return ResourceManager.GetString("ParameterListActionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string PrintManagerDate {
            get {
                return ResourceManager.GetString("PrintManagerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string PrintManagerTime {
            get {
                return ResourceManager.GetString("PrintManagerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string SensorsCheckActionInfo {
            get {
                return ResourceManager.GetString("SensorsCheckActionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature sensors S01 and S04 inverted ähnelt.
        /// </summary>
        internal static string SensorsCheckActionSensorsNotOK {
            get {
                return ResourceManager.GetString("SensorsCheckActionSensorsNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature sensors S01 and S04 Ok ähnelt.
        /// </summary>
        internal static string SensorsCheckActionSensorsOK {
            get {
                return ResourceManager.GetString("SensorsCheckActionSensorsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Circ ähnelt.
        /// </summary>
        internal static string TimeOverviewCirc {
            get {
                return ResourceManager.GetString("TimeOverviewCirc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die from ähnelt.
        /// </summary>
        internal static string TimeOverviewFrom {
            get {
                return ResourceManager.GetString("TimeOverviewFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HC ähnelt.
        /// </summary>
        internal static string TimeOverviewHC {
            get {
                return ResourceManager.GetString("TimeOverviewHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeRaster ähnelt.
        /// </summary>
        internal static string TimeOverviewTimeRaster {
            get {
                return ResourceManager.GetString("TimeOverviewTimeRaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeOverview ähnelt.
        /// </summary>
        internal static string TimeOverviewTitle {
            get {
                return ResourceManager.GetString("TimeOverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        internal static string TimeOverviewTo {
            get {
                return ResourceManager.GetString("TimeOverviewTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        internal static string UnitDays {
            get {
                return ResourceManager.GetString("UnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        internal static string UnitHours {
            get {
                return ResourceManager.GetString("UnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min. ähnelt.
        /// </summary>
        internal static string UnitMinutes {
            get {
                return ResourceManager.GetString("UnitMinutes", resourceCulture);
            }
        }
    }
}
