using System.Diagnostics.CodeAnalysis;


[module: SuppressMessage("Microsoft.Design", "CA1050:DeclareTypesInNamespaces", Scope="type", Target="SunPosition")]
[module: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope="type", Target="SolvisSC2Viewer.CircMode")]
[module: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope="member", Target="SolvisSC2Viewer.HeatCircuitSettings.#GetHeatCircuit()")]
[module: SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[module: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope="member", Target="SolvisSC2Viewer.AboutDialog.#MakeTabItem(System.String,System.String,System.Windows.Forms.TextBox)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope="member", Target="SolvisSC2Viewer.ConfigReader.#ParseElements(System.Collections.Generic.IDictionary`2<System.String,SolvisSC2Viewer.ConfigData>,System.Xml.XmlNode,System.String)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope="member", Target="SolvisSC2Viewer.ConfigReader.#Parse(System.String)")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="SolvisSC2Viewer.RowValues.#FormulaIst_Soll1")]
[module: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="SolvisSC2Viewer.RowValues.#FormulaIst_Soll2")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="SolvisSC2Viewer.ICalculator.#FormulaSolarVSG(SolvisSC2Viewer.RowValues)", MessageId="VSG")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="SolvisSC2Viewer.RowValues.#SolarVSG", MessageId="VSG")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="type", Target="System.Windows.Forms.DataVisualization.Charting.MsChartExtension", MessageId="Ms")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="SolvisSC2Viewer.SolarMode.#dt", MessageId="dt")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="SolvisSC2Viewer.ICalculator.#HasFormulaSolarVSG", MessageId="VSG")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope="resource", Target="SolvisSC2Viewer.HeatCurve.resources", MessageId="Solvis")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope="resource", Target="SolvisSC2Viewer.Properties.Resources.resources", MessageId="zeitplan")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope="resource", Target="SolvisSC2Viewer.Properties.Resources.resources", MessageId="Solvis")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope="resource", Target="SolvisSC2Viewer.SensorsActors.resources", MessageId="Ist")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope="resource", Target="SolvisSC2Viewer.SensorsActors.resources", MessageId="Soll")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope="resource", Target="SolvisSC2Viewer.ConfigEditor.resources", MessageId="Solvis")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope="resource", Target="SolvisSC2Viewer.ExtrasMenuItem.resources", MessageId="Infos")]

[module: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope="member", Target="SolvisSC2Viewer.ConfigManager.#appConfigFile")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope="member", Target="SolvisSC2Viewer.HelpMenuItem.#LoadIcons()")]
[module: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope="member", Target="SolvisSC2Viewer.ExtrasMenuItem.#LoadIcons()")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="SolvisSC2Viewer.MetaProp.#Attributes")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="SolvisSC2Viewer.PropertiesForm.#SelectedObjects")]
[module: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Scope="member", Target="SolvisSC2Viewer.ParameterListAction.#Execute(SolvisSC2Viewer.ActionData)", MessageId="heatingSettings")]
[module: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Scope="member", Target="SolvisSC2Viewer.ParameterListAction.#Execute(SolvisSC2Viewer.ActionData)", MessageId="solarSettings")]
[module: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Scope="member", Target="SolvisSC2Viewer.DataManager.#DeSerialize()", MessageId="list")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.PrintProperty.#get_HeatingUser()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.CodeBuilder.#FieldVariable(System.String,System.String,System.CodeDom.MemberAttributes)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.RowValues+LogInfos.#get_LogFormat()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.RowValues+LogInfos.#get_Softwareversion()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.DataManager.#Serialize()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.AppManager.#get_HelpManager()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.RowValues+LogInfos.#get_SolvisSystem()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.DataManager.#DeSerialize()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.ConfigManager.#get_Parameters()")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.CodeBuilder.#WriteLine(System.String,System.Object[])")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="SolvisSC2Viewer.CalculatorProxy.#get_Calculator()")]

[module: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", Scope="member", Target="SolvisSC2Viewer.HeatingSettings.#.ctor(System.Collections.Generic.IList`1<System.Int32>)", MessageId="list")]
